#! /bin/sh -x

case "$1" in
  deconfig)
    ;;
  bound)
    ifconfig ${interface} ${ip} netmask ${subnet}
    if [ "${interface}" = "eth0" ]; then
      route add -net default gw ${router}
    fi
    if [ -s /tmp/lastip.${interface} ]; then
      OLDIP=$(cat /tmp/lastip.${interface})
      if [ "${OLDIP}" != "${ip}" ]; then
        /sbin/reboot
      fi
    fi
    echo "${ip}" > /tmp/lastip.${interface}
    ;;
  renew)
    ;;
  nak)
    ;;
esac
